# Generated by Django 2.2 on 2021-10-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
    ]
