# Generated by Django 2.2 on 2021-10-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabaseApp', '0002_auto_20211008_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobby',
            new_name='MyHobbys',
        ),
    ]
