# Generated by Django 2.2 on 2021-10-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabaseApp', '0004_auto_20211010_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(max_length=200)),
                ('ContactEmail', models.CharField(max_length=200)),
                ('ContactMessage', models.CharField(max_length=200)),
            ],
        ),
    ]
