# Generated by Django 2.2 on 2021-10-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobbies',
        ),
    ]
